### ISSUE TITLE
v6_06_01 does not clone git submodule for sbncode

### ISSUE THREAD

**Issue by Temigo** [art-framework-suite/mrb#13]
**Describe the bug**
this is a follow-up on [PR#12](https://github.com/art-framework-suite/mrb/pull/12). @chissg made changes to enable git submodule initialization in `gitCheckout` but I cannot get it to work as expected.

**To Reproduce**
> -bash-4.2$ unsetup mrb
> -bash-4.2$ setup mrb v6_06_01
> -bash-4.2$ which mrb
/scratch/icarus/ldomine/products/mrb/v6_06_01/bin/mrb
> -bash-4.2$ mrb g sbncode%https://github.com/Temigo/sbncode.git
Cloning into 'sbncode'...
remote: Enumerating objects: 23010, done.
remote: Counting objects: 100% (470/470), done.
remote: Compressing objects: 100% (213/213), done.
remote: Total 23010 (delta 287), reused 405 (delta 256), pack-reused 22540
Receiving objects: 100% (23010/23010), 33.26 MiB | 16.48 MiB/s, done.
Resolving deltas: 100% (16872/16872), done.
NOTICE: Adding sbncode to CMakeLists.txt file
> -bash-4.2$ ls sbncode/sbncode/Supera/
-bash-4.2$

Am I missing something in the way I setup your new version of mrb? I copied the tarball, added the path to my `$PRODUCTS` environment variable and then used `unsetup/setup` to make sure I was using your new version of mrb.

**Comment by chissg** [comment]
Please add the `-v` option to your `mrb g` invocation: `mrb g -v sbncode`. You should see extra messages, including (hopefully):
```.console
VERBOSE: Executing clone command: git clone --recurse-submodules https://github.com/SBNSoftware/sbncode.git sbncode.
```

Please provide a standalone `git clone` command that displays the behavior you require.

**Comment by Temigo** [comment]
I guess I will just put a note in the `sbncode` README to warn people about that subtle behavior change, and instructing them on how to initialize git submodules if they are cloning from a fork. Thanks for the help!!

**Comment by chissg** [comment]
I am working on providing the inheritance behavior one would expect, but it was not ready by Friday as I would have hoped.,

**Comment by chissg** [comment]
Please try [MRB v6_07_00](https://scisoft.fnal.gov/scisoft/packages/mrb/v6_07_00/). The following should all have the desired effect:
*  `mrb g https://github.com/Temigo/sbncode.git`
* `mrb g sbncode%Temigo/`
* `mrb g sbncode%github:Temigo/`
* `mrb g sbncode%github:Temigo/sbncode.git`

Please enter a new issue if you encounter any problems.
