### ISSUE TITLE
mrb g -g <githuborg> <repo> doesn't respect <githuborg>

### ISSUE THREAD

**Issue by nusense** [art-framework-suite/mrb#15]
example:   mrb g -g nusense larsim
checked out larsim from LArSoft org, not my nusense fork of the repo

<pre>[remote "origin"]
	url = git@github.com:LArSoft/larsim.git
	fetch = +refs/heads/*:refs/remotes/origin/*
</pre>

**Comment by chissg** [comment]
From https://github.com/art-framework-suite/mrb/commit/4a64794dc6680f3c8cd115a06eb07ae45f3f8f19:

> Note, as a workaround, the following implements the same behavior on a
> per-product basis as intended by the global option `--github-org`:
>
> ```
> mrb g larsim%nusense/
> ```

**Comment by chissg** [comment]
@garren Would you be able to install MRB `v6_07_08` on CVMFS, please?

**Comment by lgarren** [comment]
@chissg this will be added as part of this weeks larsoft distribution since I don't think there is a pressing need to install it immediately.  By then, there might be a second release with additions to repositories recognized by gitCheckout.
