### ISSUE TITLE
--github-org does not work with mrb g in v6_07_09

### ISSUE THREAD

**Issue by tomjunk** [art-framework-suite/mrb#16]
Using mrb v6_07_09, if I execute:

mrb g --repo-type github --github-org DUNE dunendlar

I get this message:

Cloning into 'dunendlar'...
remote: Not Found
fatal: repository 'https://github.com/dunendlar.git/' not found
ERROR: unable to execute clone command: git clone https://github.com/dunendlar.git dunendlar

which seems to be missing the DUNE part in the URL.  In my script making a new test release, I backed out to an earlier version of mrb for just the clone and it works:

unsetup mrb
setup mrb v6_03_00
mrb g --repo-type github --github-org DUNE dunendlar
unsetup mrb
setup mrb v6_07_09

.. continue with build.

**Comment by chissg** [comment]
@tomjunk Looking at this now. In the meantime as a workaround, you can do `mrb g github:DUNE/dunendlar`.
