### ISSUE TITLE
DUNE would like to add sandreco to the list of repositories known to MRB

### ISSUE THREAD

**Issue by tomjunk** [art-framework-suite/mrb#20]
**What problem are you trying to solve?**
DUNE is bringing sandreco software under its management in GitHub and would like to start building it with mrb.

**Describe your feature request**
We would like sandreco to be added to the list of repositories mrb knows to get from github.com/DUNE by default.

We can clone sandreco with these options but would like them to be the default

mrb g -b develop --repo-type github --github-org DUNE sandreco

when issuing

mrb g sandreco

We have additional work to do to get sandreco built with mrb (like add ups/product_deps and adjusting makefiles), but we can get this started.

**If this is a high-priority issue**
Not urgent.

**Comment by lgarren** [comment]
mrb v6_08_04 is now available on SciSoft and larsoft cvmfs
