### ISSUE TITLE
Would like dunetrigger added to dune_suite and also known to mrb's gitcheckout

### ISSUE THREAD

**Issue by tomjunk** [art-framework-suite/mrb#21]
We have a new dune product called dunetrigger and would like to check it out of GitHub

The repository dunetrigger is in the DUNE github organization.  I can check it out using mrb thus:

mrb g --repo-type github --github-org DUNE dunetrigger

we would like 

mrb g dunetrigger

to do the same thing.  We would also like dunetrigger added to the list of repositories checked out when doing

mrb g dune_suite

**Comment by lgarren** [comment]
Tom, since this is for mrb, would you make a redmine issue please?  I mean, we can do it from here, but we're still using redmine for this sort of thing.

**Comment by knoepfel** [comment]
@lgarren, all issues for https://github.com/art-framework-suite repositories are managed in GitHub.  MRB is one of those repositories.

**Comment by lgarren** [comment]
Sorry everyone.  Since mrb is ups only, I think of it as needing a redmine ticket.  Will make the changes.

**Comment by lgarren** [comment]
mrb v6_09_07 is now available and installed on larsoft cvmfs
