### ISSUE TITLE
new DUNE repositories in GitHub -- request changes to gitCheckout

### ISSUE THREAD

**Issue by tomjunk** [art-framework-suite/mrb#6]
**What problem are you trying to solve?**
DUNE is splitting its large dunetpc repository up and moving the pieces to GitHub.  We would like mrb g to locate the repositories when their names are specified.

**Describe your feature request**
The following repositories are new and will be populated in early January, after users have had some warning time to merge their branches.  The organization they are in is

https://github.com/DUNE

list of new repository names:

dunecore
duneopdet
dunesim
dunecalib
duneprototypes
dunedataprep
dunereco
duneana
duneexamples
dunesw

We are also moving the contents of the following two repositories from Redmine to GitHub, also in the DUNE organization:

duneutil
protoduneana

We haven't migrated these yet but can do so quickly as no changes are needed to them (except removing a couple of files from duneutil).

The request is for the appropriate changes to be made in gitCheckout so the new repositories and new locations are found by default.

**If this is a high-priority issue**
Not hit priority.  Need by early January.

**Comment by lgarren** [comment]
@tomjunk Will dunetpc remain in redmine?  Is it going to be retired?

**Comment by lgarren** [comment]
mrb v5_19_08 is now available on larsoft cvmfs.  It will get the new repositories listed above from github.  The defaults for duneutil and protoduneana remain on redmine.  You can easily tell mrb to use github instead.

Also, once the new repositories are populated, we can create a dune_suite that will checkout everything of interest.

**Comment by lgarren** [comment]
After consultation, mrb  v5_19_09 with dune_suite is now available.
