### ISSUE TITLE
mrbsetenv fails with mrb v6_02_03

### ISSUE THREAD

**Issue by cjbackhouse** [art-framework-suite/mrb#9]
From a dunegpvm (same happens on, at least, sbnd gpvms)

<pre>
source /cvmfs/dune.opensciencegrid.org/products/dune/setup_dune.sh
mkdir /tmp/dev/
cd /tmp/dev/
mrb newDev -v v09_42_04 -qe20:prof
source localProducts*/setup
mrbsetenv
</pre>

Result

<pre>
The working build directory is /tmp/dev/build_slf7.x86_64
The source code directory is /tmp/dev/srcs
----------- check this block for errors -----------------------
Can't locate Algorithm/Diff.pm in @INC (@INC contains: /cvmfs/larsoft.opensciencegrid.org/products/mrb/v6_02_03/libexec /cvmfs/larsoft.opensciencegrid.org/products/mrb/v6_02_03/slf7.x86_64/CPAN/lib/perl5/5.16.3/x86_64-linux-thread-multi /cvmfs/larsoft.opensciencegrid.org/products/mrb/v6_02_03/slf7.x86_64/CPAN/lib/perl5/5.16.3 /cvmfs/larsoft.opensciencegrid.org/products/mrb/v6_02_03/slf7.x86_64/CPAN/lib/perl5/x86_64-linux-thread-multi /cvmfs/larsoft.opensciencegrid.org/products/mrb/v6_02_03/slf7.x86_64/CPAN/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /cvmfs/larsoft.opensciencegrid.org/products/mrb/v6_02_03/slf7.x86_64/CPAN/lib/perl5/Text/Diff.pm line 8.
BEGIN failed--compilation aborted at /cvmfs/larsoft.opensciencegrid.org/products/mrb/v6_02_03/slf7.x86_64/CPAN/lib/perl5/Text/Diff.pm line 8.
Compilation failed in require at /cvmfs/larsoft.opensciencegrid.org/products/mrb/v6_02_03/libexec/Cetmodules/CMake.pm line 20.
BEGIN failed--compilation aborted at /cvmfs/larsoft.opensciencegrid.org/products/mrb/v6_02_03/libexec/Cetmodules/CMake.pm line 20.
Compilation failed in require at /cvmfs/larsoft.opensciencegrid.org/products/mrb/v6_02_03/libexec/setup_products line 34.
BEGIN failed--compilation aborted at /cvmfs/larsoft.opensciencegrid.org/products/mrb/v6_02_03/libexec/setup_products line 34.
-bash: .: filename argument required
.: usage: . filename [arguments]
ERROR: setup of required products has failed
</pre>

**Comment by chissg** [comment]
Apologies for the oversight. This  problem is actually in cetmodules, and will be fixed with an imminent update configuring the Perl dependency scanner to scan recursively.

**Comment by lgarren** [comment]
We have removed cetmodules v3_05_04 and mrb v6_02_03 from larsoft cvmfs while we wait for the proper fix.

**Comment by lgarren** [comment]
I'm setting up to test this when we get a fix.  It appears that the uboonegpvm machines do not have a problem.  Just FYI.

**Comment by lgarren** [comment]
mrb v6_03_00 and cetmodules v3_06_00 are now installed on larsoft cvmfs.  They have been tested on a dunegpvm machine.  No problems were found.
